title: Khoa Nguyen Xuan
description: >-
  Security researcher obsessed with breaking things. Personal blog about
  fuzzing for bugs, vulnerability research, and low-level engineering.
author:
  name: Khoa Nguyen Xuan
  github: khoanguyenxuan
baseurl: ""
url: "https://khoanguyenxuan.github.io"
theme: jekyll-theme-hacker
show_downloads: false
